# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://blog.pospieszynski.net" # the base hostname & protocol for your site
permalink: /:year/:month/:day/:title
excerpt_separator: "<!--more-->"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: HomePage | Jacek Pospieszyński
  avatar: avatar.png
  gravatar: # Email MD5 hash
  description: "Mój osobisty blog o starciach z programowaniem i nie tylko - Jacek Pospieszyński " # used by search engines

  # Header and footer text
  header_text: 
  header_text_feature_image:
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>

  # Icons
  rss: false
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "pospieszja"
  google_plus:
  instagram:
  linkedin: https://www.linkedin.com/in/jacek-pospieszy%C5%84ski-460ba54b/
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: 
  wordpress:
  youtube:

  # Scripts
  google_analytics: UA-91548956-2
  disqus_shortname: pospieszynski-net
  muut_community_name: # From muut.com settings, e.g. "muttcommunityname"
  katex: # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Następne"
  str_prev: "Poprzednie"
  str_continue_reading: "Czytaj dalej"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
gems: 
  - jekyll-paginate
  - jekyll-seo-tag
